<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   bayer
 * @package    Bayer_AustrianLaw
 * @subpackage Module
 * @copyright  Copyright (c) 2017 Daniel Reichhard
 * @author     Florian Sydekum <f.sydekum@techdivision.com>
 * @author     Daniel Reichhard <daniel.reichhard@gmail.com>
 */
namespace bayer\AustrianLaw\Block;

/**
 * @var $block \bayer\AustrianLaw\Block\AfterPrice
 */
?>
<?php if (!$block->isEnabled() || !$block->isAsterisk()) return; ?>

<span class="tax-details">
    * <?php echo $block->getTaxText() ?>
</span>
